// July 2026 devotional data — "Meditations of the God-Kind" booklet, transcribed.
//
// This is a plain data file. To import it into Sanity, run:
//   node --env-file=.env.local scripts/import-devotionals.mjs scripts/devotionals-data/2026-07.mjs
//
// For a new month: copy this file to e.g. 2026-08.mjs, replace the entries below
// (each needs: date, title, scripture, verseText, discussion[]; optional: confession,
// pray, meditationScripture, meditationText, action), then run the command above
// pointing at the new file. See scripts/import-devotionals.mjs for field details.

export const DEVOTIONALS = [
  {
    date: "2026-07-01",
    title: "It's Practical",
    scripture: "Jas 2:14",
    verseText:
      "Dear brothers and sisters, what's the use of saying you have faith if you don't prove it by your actions? That kind of faith can't save anyone. (NLT)",
    discussion: [
      'Christianity is practical. What\'s the use saying you are a Christian if you don\'t prove it by your actions? What a great deception in our day, where people can do church in the day and club at night without any remorse. What a day where people can be homosexuals and lead worship in church comfortably. This is not to condemn you at all but to judge you. Stop kidding yourself with that "stop judging me" mantra. Believers have been authorized by God to judge several things including each other. Not condemnation but judgement unto repentance. Read this: 1Cor.5.9-13; "When I wrote to you before, I told you not to associate with people who indulge in sexual sin. But I wasn\'t talking about unbelievers who indulge in sexual sin, or who are greedy or are swindlers or idol worshipers. You would have to leave this world to avoid people like that. What I meant was that you are not to associate with anyone who claims to be a Christian yet indulges in sexual sin, or is greedy, or worships idols, or is abusive, or a drunkard, or a swindler. Don\'t even eat with such people. It isn\'t my responsibility to judge outsiders, but it certainly is your job to judge those inside the church who are sinning in these ways. God will judge those on the outside; but as the Scriptures say, \'You must remove the evil person from among you.\'" (NLT)',
      "To be a believer is much more than loving church music and attending a celebrity studded church. It's practical. If your closest relationships such as family, colleagues and spouses can't boldly submit that you're born again, then you probably are not. Divine love and wisdom are practical. If you're constantly disrespectful to your husband/violent to your wife/cheating on your spouse/unfaithful to your boss/cheating in exams/getting money through dubious means/quarrelsome with your neighbours/unjust to your staff, etc, you need to repent. Whoever said you could live in sin and claim Christianity lied to you. Read the NLT translation of James 3:15-17.",
      "Certain lifestyles are motivated by the devil. It doesn't matter what you're confessing, if you continuously do these things, you're the devil's pawn. Repent today and shine the light you truly are! Maybe you know somebody who needs to read this, forward it to them. Shalom Uvracha!",
    ],
    pray: "Father, I repent of every behaviour that is contrary to your Word.",
    meditationScripture: "Jas 2:14",
    meditationText:
      "Dear brothers and sisters, what's the use of saying you have faith if you don't prove it by your actions? That kind of faith can't save anyone. (NLT)",
  },
  {
    date: "2026-07-02",
    title: "Helpers Get Help",
    scripture: "Rom. 16:1",
    verseText: "I commend unto you Phebe our sister, which is a servant of the church which is at Cenchrea.",
    discussion: [
      'Romans chapter 16 is a very interesting chapter in the bible. It lists out some very interesting names. These were men and women who were exceptionally helpful to Paul and to the churches. The first person mentioned is Phebe, a dear sister and a deaconess of the church at Cenchrea. Paul writes to the churches in Rome to assist Deaconess Phebe in whatever she needs as she visits Rome. Surely, Phebe wasn\'t the only member of the church in Cenchrea, but Paul earnestly admonished the churches in Rome to be of help to Phebe because Phebe had been of exceptional help to Paul and the saints in the church in Cenchrea. Rom.16.1-2; "Our sister Phoebe, a deacon in the church in Cenchrea, will be coming to see you soon. Receive her in the Lord, as one who is worthy of high honour. Help her in every way you can, for she has helped many in their needs, including me." (NLT) See why Paul charges the saints in Rome to help Phebe? \'For she has helped many in their needs, including me\'. This is something to pay attention to today. Help begets help. A helper attracts helpers. If you haven\'t been helping the saints in your local assembly, why do you expect helpers to rise up to your aid in time of need? This is not to say we should only help those who help us. Not at all. Get the point.',
      "The church helps everyone; saints come to the aid of everyone in need. But understand that the one who has been of help to saints in their time of need will obviously be etched in the hearts of saints so that they arise to help such a one in times of their own need. In our day where people leave churches for every little thing such as not being visited by the church when they were ill. The question is how many people did you also visit when they were ill? The church didn't look for you. How many people have you looked for? They didn't give you rice at Christmas. How many people have you given rice or even a glass of water? Why should you always be the charity case? Can't you grow up and become the helper of saints such that they'll never forget your good deeds. And even if they do, God never forgets (Hebrews 6:10). We spend so much time in prayer asking God to send us helpers. What about asking God to lead you to help someone in need. Don't you understand that it is more fulfilling to give than to receive (Acts 20:35). From today, focus on helping others, then watch and see how help will also come to you. (Acts 9:36-40, Prov. 11:25).",
    ],
    meditationScripture: "Heb. 6:10",
    meditationText:
      "For God is not unrighteous to forget your work and labour of love, which ye have shewed toward his name, in that ye have ministered to the saints, and do minister.",
  },
  {
    date: "2026-07-03",
    title: "Go in This Revelation",
    scripture: "Judg. 6:13",
    verseText:
      "\"Sir,\" Gideon replied, \"if the LORD is with us, why has all this happened to us? And where are all the miracles our ancestors told us about? Didn't they say, 'The LORD brought us up out of Egypt'? But now the LORD has abandoned us and handed us over to the Midianites.\" (NLT)",
    discussion: [
      '"If I have been delivered, why am I going through this problem?". "If God has healed me, why am I still feeling the pains?" "If God has answered my prayers, why am I still in so much lack?" These are legitimate questions dear believers ask daily. Make no mistake about it, the gorgeous attires adorned by many on Sundays do a great job of covering the pains, heart aches and questions in the hearts of people. The bible tells us of a man called Gideon who had similar questions. There\'s much to learn from his experience with God. The angel of God appeared to Gideon and addressed him as \'thou mighty man of valour, the Lord is with you.\' This baffled Gideon. How could the Lord be with him if he and his family and the entire Israel were slaves of the Midianites. Fear and oppression plagued the land, and his family had it worse being little and poor. Judg.6:13; "Sir," Gideon replied, "if the LORD is with us, why has all this happened to us? And where are all the miracles our ancestors told us about? Didn\'t they say, \'The LORD brought us up out of Egypt\'? But now the LORD has abandoned us and handed us over to the Midianites." (NLT) I\'ve heard of God\'s miracles. I\'ve read about God\'s powerful works in people\'s lives. I hear these testimonies daily.',
      'But why isn\'t it happening to me? This was Gideon\'s question. God doesn\'t respond to him with an explanation... but with an instruction based on a revelation. Read Judg.6.14-16 (NLT). The LORD said to him, "I will be with you. And you will destroy the Midianites as if you were fighting against one man." Glory! An explanation of your woes does not empower you for success. What you need is a divine instruction from the place of divine revelation. The angel of God revealed 3 things to Gideon that day; (1) You are a mighty man. (2) I am with you. (3) I have commanded you to destroy Midian. This is what God referred to as \'Go in this thy might\'. Go in the strength of the revelation you have received. This is God\'s instruction to you today. Don\'t gripe and sulk, get up and go in this revelation, for you shall smite Midian as one man. It doesn\'t matter what has/hasn\'t happen before now, if you would go in the revelation of who God says you are and what He says you should do, you will come back with great testimonies. Shalom Uvracha!',
    ],
    meditationScripture: "Judg. 6:14",
    meditationText:
      "And the LORD looked upon him, and said, Go in this thy might, and thou shalt save Israel from the hand of the Midianites: have not I sent thee?",
  },
  {
    date: "2026-07-04",
    title: "Wisdom and Folly",
    scripture: "Prov. 9:8",
    verseText: "Reprove not a scorner, lest he hate thee: rebuke a wise man, and he will love thee.",
    discussion: [
      'The book of proverbs reveals two entities we all generally listen to. The actions we take are indicative of the entity we have listened to. Counsel from each of these two entities always leads to opposing destinations; fulfilment or destruction. First is Lady Wisdom. Wisdom beckons on passersby to listen, learn and be preserved from destruction; Prov.9.1-6 (NLT). Wisdom calls out to those who will respond, and makes them wise and prosperous in life. Prov.9.10-12; "Fear of the LORD is the beginning of wisdom. Knowledge of the Holy One results in understanding. Wisdom will multiply your days and add years to your life. If you become wise, you will be the one to benefit. If you scorn wisdom, you will be the one to suffer."',
      'On the other hand, there is Lady Folly, who also calls out to those who would respond, but the call of folly is different. Folly counsels you to engage in sharp practices; steal, commit adultery and to pervert judgement. Prov.9.13-18 (NLT). Wisdom counsels you to fear God and keep His commands, but Folly lures you into worldly lusts. Beloved, those who listen to the counsel of Folly always end up in destruction.',
      'Folly feels adventurous with much excitement and immediate gratification; "stolen waters are sweet and food eaten in secret is pleasant", but Folly has only one end for her listeners; death; "But he knoweth not that the dead are there; and that her guests are in the depths of hell." (Prov 9:18) Turn away from folly and listen to wisdom! Shalom Uvracha!',
    ],
    confession: "I refuse to listen to the voice of folly. I walk in divine wisdom always. Amen!",
    meditationScripture: "Prov. 9:16-18",
    meditationText:
      "Whoso is simple, let him turn in hither: and as for him that wanteth understanding, she saith to him, Stolen waters are sweet, and bread eaten in secret is pleasant. But he knoweth not that the dead are there; and that her guests are in the depths of hell.",
  },
  {
    date: "2026-07-05",
    title: "All You Need Is 300",
    scripture: "Judg. 7:7",
    verseText:
      "And the LORD said unto Gideon, By the three hundred men that lapped will I save you, and deliver the Midianites into thine hand: and let all the other people go every man unto his place.",
    discussion: [
      "Gideon had an army of 32,000-foot soldiers marching on to war against the army of Midian. Gideon was ready to go to war with this large army, but God had different plans. God gave Gideon an instruction on strategies to cut down the army. Gideon had 32,000 soldiers, but God needed only 300 men. The process of cutting down the army must have been alarming to Gideon. Imagine already being afraid to march out with 32,000 soldiers, then God says cut the number down to 300 soldiers. If you weren't sure of victory with 32,000 soldiers, what hope do you have with only 300 soldiers? But that's where God's ways differ from men's. With a larger number, there was the temptation to attribute victory to the size of your army. But when victory comes against all odds, you know IT CAN ONLY BE GOD! Some of the things you're going through right now is God cutting out everything and everyone that would want to take the coming glory. You lost jobs; somebody left you; people disappointed you; they promised and failed you...etc. Do not despair dear saint, you thought you needed 32,000 people, but God only needs 300.",
      'You thought you needed all those people, but God needs just your heart of faith. The people God sends to you are the people you need. The people you are pursuing here and there are usually the people you don\'t need. Sometimes we spend too much energy trying to keep what God is removing from our lives. In the words of Bishop T D Jakes; "If people can walk out of your life, LET THEM WALK!" Stop begging people to stay. Even concerning the kingdom, there\'s the place for follow up and seeking out the deviating brother, but there\'s also the place for God to cut off the false brethren from His church; 1John.2.19; "They went out from us, but they were not of us; for if they had been of us, they would no doubt have continued with us: but they went out, that they might be made manifest that they were not all of us." Never forget this counsel today, God does not need all you think you need; all God needs to bring about that miracle you desire is your heart of faith. It\'s from here divine instructions and connections will come. You don\'t need 32,000, all you need is 300. Shalom Uvracha!',
    ],
    meditationScripture: "Judg. 7:2",
    meditationText:
      "GOD said to Gideon, \"You have too large an army with you. I can't turn Midian over to them like this--they'll take all the credit, saying, 'I did it all myself,' and forget about me.\" (MSG)",
  },
  {
    date: "2026-07-06",
    title: "Unchanging Words",
    scripture: "Judg. 11:35",
    verseText:
      "When he saw her, he tore his clothes in anguish. \"My daughter!\" he cried out. \"My heart is breaking! What a tragedy that you came out to greet me. For I have made a vow to the LORD and cannot take it back.\" (NLT)",
    discussion: [
      'Jephtha made a vow to God and this was his vow; Judg.11.30-31; ".. If you give me victory over the Ammonites, I will give to the LORD the first thing coming out of my house to greet me when I return in triumph. I will sacrifice it as a burnt offering." (NLT) So, Jephthah went out to war and the Lord granted his request by giving him a resounding victory over the Ammonites. Jephtha and his army came back rejoicing, and in approaching his house with great joy, his daughter was the very first thing/person to come out of his house to greet him. One would question the sanity of such a vow, but the vow isn\'t the subject of discussion today. The focus is Jephthah\'s commitment to his vow even when the consequences were particularly grievous to him. His one and only daughter and only child came out to greet him. If Jephthah was like the majority of us in our day, he\'d have found a reasonable explanation to excuse himself from fulfilling his vows. Read again Jephthah\'s response in Judg.11.35 (NLT). Take note of the words; "I HAVE MADE A VOW TO THE LORD AND CANNOT TAKE IT BACK." The vow he made were just mere words that could have been changed at will. But that\'s where the problem is. No such thing as mere words.',
      'The word of a man is the man himself. Your word is your integrity. Your word is who you are. This is why the bible shows us in very many ways that our word is the power we need to make a difference in our world (Prov 18:21, Matt 11:23). Isaac blessed his sons using words and his words came to pass. So did Jacob. Elisha used his words to call out a curse on his mockers and it was fulfilled instantly. Elijah spoke and fire fell on his assailants. Paul spoke and Elymas the sorcerer went blind. And the list goes on. The reason our words seem not to carry as much power as the words of men of old is because we change our words faster than the time on a ticking clock. If you don\'t take your words seriously, your world will not take your words seriously. The seriousness you give to your words, is the seriousness the elements of life will give to your words. This is why Jesus says to us; "..let your yes be yes and your no be no!" (Matt 5:36-37). Begin the process of seriously taking your words seriously. If you say something, commit to it until you see it through. You cannot be unfaithful with your words on one hand, then expect your words to faithfully come to pass on the other hand. Commit to unchanging words from today. Shalom!',
    ],
    confession: "My words are powerful. I commit to being faithful with my words from now on. Amen!",
  },
  {
    date: "2026-07-07",
    title: "Hating You",
    scripture: "1 John 3:13",
    verseText: "Marvel not, my brethren, if the world hate you.",
    discussion: [
      'Dear brethren, marvel not if the world hates you. The system of this world is antithesis to the ways of God. The system of this world is built on three things; the lust of the flesh, the lust of the eyes, and the pride of life. 1John.2.15-16; "Love not the world, neither the things that are in the world. If any man love the world, the love of the Father is not in him. For all that is in the world, the lust of the flesh, and the lust of the eyes, and the pride of life, is not of the Father, but is of the world." That is; strong desire to have what you feel, strong desire to get what you see, and strong desire to be better than others in achievements and possessions. It\'s a system of carnal pursuits and vanities upon vanities. This system turns against any sign of righteousness. This is why anyone who truly loves God and lives righteously will be hated by the world. John.15.18-19; "If the world hate you, ye know that it hated me before it hated you. If ye were of the world, the world would love his own: but because ye are not of the world, but I have chosen you out of the world, therefore the world hateth you." Many believers try to be loved by all. Truly, no one ordinarily loves to be hated, so we try to do as much as possible to be loved and accepted by the world. We must correct this now! There\'s no value in being loved by those who hate Jesus. If they hate Jesus, they\'ll hate you too.',
      'You are his express image in all things. Be comfortable with being hated for Christ\'s sake. Be glad when you\'re mistreated because of your righteous stand. Now, be careful not to have a persecution complex. Maybe your boss reprimands you for irresponsible behaviour, then you claim you\'re being persecuted. If you suffer for doing wrong, you\'re not being persecuted, you\'re being corrected. Suffering for righteousness means doing the right thing in the name of Jesus Christ and suffering for it. Never mix it up. 1Pet.2.19-20; "For it is commendable if a man bears up under the pain of unjust suffering because he is conscious of God. But how is it to your credit if you receive a beating for doing wrong and endure it? But if you suffer for doing good and you endure it, this is commendable before God." (NIV) Therefore, in conclusion, don\'t be alarmed or depressed when you\'re hated. Become very comfortable with being hated and spoken against. If you\'re hated for being an ambassador of Christ, rejoice and shine your light brighter. Shalom Uvracha!',
    ],
    meditationScripture: "1 Pet. 2:21",
    meditationText:
      "To this you were called, because Christ suffered for you, leaving you an example, that you should follow in his steps. (NIV)",
  },
  {
    date: "2026-07-08",
    title: "Daily Bread",
    scripture: "Matt. 6:11",
    verseText: "Give us this day our daily bread.",
    discussion: [
      'Deut.8.3; "And he humbled thee, and suffered thee to hunger, and fed thee with manna, which thou knewest not, neither did thy fathers know; that he might make thee know that man doth not live by bread only, but by every word that proceedeth out of the mouth of the LORD doth man live." God fed the Israelites with Manna in the wilderness. It was supernaturally produced. It simply just appeared at their doorsteps every morning as the morning dew evaporated. In Deuteronomy 8:3, Moses explained to the Israelites that the hunger they experienced in the wilderness was permitted by God in order to humble them and then He fed them with the supernatural manna to teach them that man doesn\'t live on bread alone but by every word that comes out of the mouth of God. So, we see that the supply of manna was a lesson to the Israelites, and of course to us. It wasn\'t simply a divine food supply but more importantly a lesson that the words from God\'s mouth are more important to man\'s life than the food that goes into his mouth. Therefore, when Jesus taught His disciples to pray saying in Matt 6:11; "Give us this day our daily bread.", He couldn\'t have been more particularly interested in physical bread and fish. The content of the prayer Jesus taught them was focused on the Father, His will and His kingdom. Matt.6:9-13; "Our Father which art in heaven, Hallowed be thy name. Thy kingdom come. Thy will be done in earth, as it is in heaven. Give us this day our daily bread. And forgive us our debts, as we forgive our debtors. And lead us not into temptation, but deliver us from evil: For thine is the kingdom, and the power, and the glory, for ever. Amen." We know that God doesn\'t give food to only children of the kingdom. He gives the whole earth food, including animals. Matt.5:45; "That ye may be the children of your Father which is in heaven: for he maketh his sun to rise on the evil and on the good, and sendeth rain on the just and on the unjust." If all creation gets their food freely from God, why then do the children of the Kingdom have to pray for daily bread? Therefore, for this to be part of the prayer made by Jesus, it must mean more than just physical food but more particularly about receiving the words out of God\'s mouth. The word of God out of God\'s mouth is our daily bread. This is called rhema. Hallelujah! Rhema is our daily bread. It is God\'s word to you for a particular situation, at a particular time. This is the word we live by. This is the word by which our spirits are nourished and strengthened to rule over each day. It\'s our daily bread. As the body without food gets weak, so the spirit without rhema gets confused. Pray today, "Father give me today my daily rhema." Shalom Uvracha!',
    ],
    meditationScripture: "Job 23:12",
    meditationText:
      "I have not departed from the commands of his lips; I have treasured the words of his mouth more than my daily bread.",
  },
  {
    date: "2026-07-09",
    title: "God's Signature",
    scripture: "Isa. 42:9",
    verseText: "Behold, the former things are come to pass, and new things do I declare: before they spring forth I tell you of them.",
    discussion: [
      'When an artist completes a painting, he/she will usually include their signature for easy recognition. The signature lets us know whose work it is. God is the ultimate artist. He created the world and left His signature on His work; Rom.1.19-20; "But the basic reality of God is plain enough. Open your eyes and there it is! By taking a long and thoughtful look at what God has created, people have always been able to see what their eyes as such can\'t see: eternal power, for instance, and the mystery of his divine being. So, nobody has a good excuse." (MSG) God hasn\'t only left His signature on the canvas of creation; He still leaves His signature on the events of our lives. Thus, if you pay close attention to the events of your life, you can tell if it\'s God at work or the devil\'s mischief making. When it\'s God at work, all you need to do is cooperate with Him by faith. But if it\'s the devil at work, your response should be to resist him by faith in God\'s word. Jas.4.7; "Submit yourselves therefore to God. Resist the devil, and he will flee from you."',
      'One way to recognize God\'s signature is in our opening verse; Isa.42.9; He says \'before they spring forth, I tell you of them.\' It\'s very much like planting a seed in the ground. After a while, the blade of its leaf springs forth out of the ground. This is the first visible sign that something was planted. This visible sign brings rejoicing. The farmer can see that his seed is growing. Harvest is in sight. But the reason he is expectant of the spring forth is because he is aware that a seed was planted. Without the planting, there is no expectation of a springing forth. The planted seed symbolizes God\'s word to you. God\'s signature is that He declares peace and good to you when there is no sign of any possibility of peace and good. He calls things as He sees them not as you see them. He says they are, when they seem not to be; Rom.4.17. That\'s God\'s signature. We find it all over the bible, and when you pay attention, you\'ll also find it in your life. If God has said it to you, even though it may not look like it right now, it will surely spring forth. God\'s word to you is the guarantee for your harvest. Shalom Uvracha!',
    ],
    meditationScripture: "Rom. 4:17",
    meditationText:
      'We call Abraham "father" not because he got God\'s attention by living like a saint, but because God made something out of Abraham when he was a nobody. Isn\'t that what we\'ve always read in Scripture, God saying to Abraham, "I set you up as father of many peoples"? Abraham was first named "father" and then became a father because he dared to trust God to do what only God could do: raise the dead to life, with a word make something out of nothing. (MSG)',
  },
  {
    date: "2026-07-10",
    title: "Your Real Worth",
    scripture: "Luke 10:20",
    verseText: "Notwithstanding in this rejoice not, that the spirits are subject unto you; but rather rejoice, because your names are written in heaven.",
    discussion: [
      'The disciples of Jesus had just returned from their mission. Sent by Jesus, they went into the neighbouring towns and villages preaching the gospel of the kingdom. When they returned, they were so excited to report how they casted out devils in the name of Jesus. But Jesus interrupted them with this statement; Luke.10.20; "Notwithstanding in this rejoice not, that the spirits are subject unto you; but rather rejoice, because your names are written in heaven." They rejoiced in what they had done, but Jesus corrects them and teaches them to rejoice in what God had done. Much more than being able to cast out devils is the joy of having your name in Heaven. The joy of being made a son of God should always exceed the joy of accomplishing great things in the kingdom of God. There are many who measure their self-worth by the things they accomplish or their material possessions. Others pride themselves in their academic achievements. Even in God\'s kingdom, there are those who measure their self-worth by the size of the congregation they pastor or the number of miracles happening through them.',
      'None of these things accurately depicts your true worth but the work done by God through Jesus in bringing you to Himself. Thus, you have been made the son of God in Christ Jesus. This is your true self-worth and the source of all your joys. Never boast about what you do for God but about what God has done for you. Yes, your authority over devils is something to shout about, but God\'s love and presence with you is something to shout louder about. Luke.10.20; "All the same, the great triumph is not in your authority over evil, but in God\'s authority over you and presence with you. Not what you do for God but what God does for you--that\'s the agenda for rejoicing." (MSG) If you would think like this, the devil will never have the grounds to make you feel depressed, disappointed or defeated. No matter what comes your way, whether your expectations were met or not, your joy remains intact, because your name is already written in heaven and ain\'t nothing that devil can do about it. Shalom Uvracha!',
    ],
    meditationScripture: "Luke 10:20",
    meditationText:
      "All the same, the great triumph is not in your authority over evil, but in God's authority over you and presence with you. Not what you do for God but what God does for you--that's the agenda for rejoicing. (MSG)",
  },
  {
    date: "2026-07-11",
    title: "The Influence of Spirits",
    scripture: "Mark 5:3-4",
    verseText:
      "Who had his dwelling among the tombs; and no man could bind him, no, not with chains: Because that he had been often bound with fetters and chains, and the chains had been plucked asunder by him, and the fetters broken in pieces: neither could any man tame him.",
    discussion: [
      'Jesus encountered a man possessed by many demons on the shores of the country of the Gadarenes. Empowered by these demon spirits, the man was able to pluck the chains asunder and break the fetters in pieces. He was literally unstoppable. How could a mortal man be this powerful? The reason was because he was empowered by demon spirits. Now, if a demon spirit could have such an unmistakable effect on a human, what about the Holy Spirit of God? Let\'s see a similar account of possession, but this time a possession of a man by the Holy Spirit. Judg.15.14; "And when he came unto Lehi, the Philistines shouted against him: and the Spirit of the LORD came mightily upon him, and the cords that were upon his arms became as flax that was burnt with fire, and his bands loosed from off his hands." The Spirit of the Lord took hold of Samson and made him unstoppable and indestructible. Possessed by the Holy Spirit, Samson broke the cords and bands the men of Judah used to tie his hands. They fell off his hands as if they were burnt strands of flax.',
      'The presence of the Holy Ghost literally burnt the cords without any effort from Samson. Hallelujah! Therefore, spirits empower humans to do the impossible. Demon spirits empower men but the Spirit of God empowers saints. So, if you want to walk in the impossible, you\'ll have to be possessed by the Spirit of God. If the Spirit of God takes hold of you, nothing will be impossible for you. This is why the scriptures admonish us to constantly be under the influence of the Holy Spirit. Eph 5:18; "Don\'t be drunk with wine, because that will ruin your life. Instead, let the Holy Spirit fill and control you." (NLT) The immediate result of this will be; Eph.5.19-20; "Then you will sing psalms and hymns and spiritual songs among yourselves, making music to the Lord in your hearts. And you will always give thanks for everything to God the Father in the name of our Lord Jesus Christ." (NLT) This will snowball into a life of good works, miracles, wonders and greater works (Acts 1:8, Acts 10:38). Dear saint, make up your mind not to live life ordinarily. To be ordinary is to be a casualty. Choose to live extraordinarily by being fully under the influence of the Holy Spirit at all times. Shalom Uvracha!',
    ],
    meditationScripture: "Acts 10:38",
    meditationText:
      "How God anointed Jesus of Nazareth with the Holy Ghost and with power: who went about doing good, and healing all that were oppressed of the devil; for God was with him.",
  },
  {
    date: "2026-07-12",
    title: "The Proper Order",
    scripture: "Jas. 4:7",
    verseText: "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
    discussion: [
      "Two instructions given to us in our opening verse. First, submit yourself to God. Second, resist the devil. Then the resultant effect, he will flee from you. It's amazing how many Christians ignore the first instruction, but attempt to follow the second instruction with a desire to get the same result. It doesn't work that way. Submission to God starts with salvation. So, I'm talking to those who are born again by believing in the resurrection of Jesus the son of God. If you aren't born again, it means you're not saved and you're heading for eternal condemnation (John 3:18). There's only one way out, His name is Jesus. If you would believe with your heart that he rose from the dead, you will be saved (Romans 10:9-10, Acts 8:36-37). That's primarily what it means to be submitted to God. But there are folks who say they believe in Jesus but live their lives contrary to the Christ they claim to believe in. These folks aren't submitted to God. Submission to God is more than mouthing religious cliches.",
      "A believer in Christ is not known by his speech alone but much more by his character. He has crucified the flesh and its lusts; Gal.5.24; \"And they that are Christ's have crucified the flesh with the affections and lusts.\" Now here's the matter at hand; you cannot get rid of the devil if you're dinning with the devil. Many people don't want to live according to the Spirit but they want to resist the devil in their lives. Not going to happen! The power to successfully resist the devil comes from submission to God. The more you live carnally, the more the devil resists your resistance. If you try to get rid of the devil in some matter in your life, but you harbour malice in your heart against anyone, or you're envious of a brother/sister, or allow lust to lead you to sexual immorality, or refuse to forgive someone who hurt you, you'll be giving power to the devil to mount resistance against your resistance. Maybe for example the devil is after your health and you're trying to receive your healing. If you refuse to let go of offence, he'll oppose you and hinder you from receiving your healing. This happens in many areas of your life. If you want to walk fully in the victory given to you in Christ Jesus, you must stop fellowshipping with the devil. Submit to God, resist the devil, and HE WILL flee from you. Shalom Uvracha!",
    ],
    meditationScripture: "Jas. 4:7",
    meditationText: "Submit yourselves therefore to God. Resist the devil, and he will flee from you.",
  },
  {
    date: "2026-07-13",
    title: "Try Again",
    scripture: "Judg. 20:18",
    verseText:
      "And the children of Israel arose, and went up to the house of God, and asked counsel of God, and said, Which of us shall go up first to the battle against the children of Benjamin? And the LORD said, Judah shall go up first.",
    discussion: [
      '"If it was God that sent you, you will surely succeed!". "If God is in it, success is sure." These are the kinds of statements we make without proper explanation of what we mean. These statements sound spiritual and powerful, but without proper understanding, they\'ll set you up for much disappointment in life. If you\'re to be truthful with yourself, you\'ll notice that there are marriages for example where each couple claim to have heard God clearly before they decided to get married to each other. Yet, they have huge problems in the marriage today. Many have started a business because they heard God, but that business is dead today, or at best struggling. Other examples abound. There is something vital we\'re missing concerning these matters. That God sent you does not exempt you from the battles ahead. God freely gave the land of Canaan to the Israelites, but they had to go in and fight the inhabiting giants. We find another account referenced in our opening verse where the other tribes of Israel went to battle against the single tribe of Benjamin. Israel enquired of the Lord and the Lord said "Go!" In fact the Lord gave them a battle strategy that required the tribe of Judah to lead the army of Israel. Israel advanced with an army of 400,000 soldiers against Benjamin\'s army of 26,700 soldiers. Backed by God\'s instruction and a large army they went and they were defeated mercilessly. Read: Judg.20.21-28; "But Benjamin\'s warriors, who were defending the town, came out and killed twenty-two thousand Israelites in the field that day. But the Israelites took courage and assembled at the same place they had fought the previous day. (For they had gone up to Bethel and wept in the presence of the LORD until evening. Then they asked the LORD, \'Should we fight against our relatives from Benjamin again?\' And the LORD said, \'Go out and fight against them.\') So, they went out to fight against the warriors of Benjamin, but the men of Benjamin killed another eighteen thousand Israelites, all of whom were experienced with a sword. Then all the Israelites went up to Bethel and wept in the presence of the LORD and fasted until evening. They also brought burnt offerings and peace offerings to the LORD. And the Israelites went up seeking direction from the LORD...The Israelites asked the LORD, \'Should we fight against our relatives from Benjamin again or should we stop?\' The LORD said, \'Go! Tomorrow I will give you victory over them.\'" They went again and finally defeated Benjamin. What\'s the lesson here? They prayed consistently, they trusted God\'s word even in the midst of failure, and they never stopped trying. Even when you have God\'s word, you may still encounter difficulties and challenges. Victory comes by holding on and never giving up. Get up and try again. The one who does not quit will see the fulfilment of God\'s word. Shalom Uvracha!',
    ],
  },
  {
    date: "2026-07-14",
    title: "Your Replacement Is Nearby",
    scripture: "1 Sam. 15:28",
    verseText: "And Samuel said unto him, The LORD hath rent the kingdom of Israel from thee this day, and hath given it to a neighbour of thine, that is better than thou.",
    discussion: [
      "God chose and anointed Saul to be king over Israel, but because of his gross misbehaviour, he was replaced by the young son of Jesse. Saul didn't know that while he was busy misbehaving, God was already grooming his replacement (1Sam.15.28). That neighbour was David. Neighbour implies one who is nearby. Saul was not aware that God cannot be held hostage neither can his plan be hijacked. While Saul was disobeying and failing his tests, David was obeying and passing his. 1Sam.16.1; \"And the LORD said unto Samuel, How long wilt thou mourn for Saul, seeing I have rejected him from reigning over Israel? Fill thine horn with oil, and go, I will send thee to Jesse the Bethlehemite: for I have provided me a king among his sons.\" Eli was another man chosen and anointed by God to be the high priest of Israel and his sons served as priests under him.",
      "God made known his plan to have Eli's descendants serve as priests in God's house forever under the old covenant. But his sons; Hophni and Phinehas began to oppress God's people and commit adultery with the female sanctuary workers. Despite warnings from God, Eli did not deal strongly with his sons. Instead, he treated them with kid gloves (1Sam.2.25). Meanwhile, Eli did not know that God was grooming his replacement, right under his nose. The next High priest and prophet of Israel was being trained by Eli himself. The one who will obey God where Eli disobeyed God was right in the neighbourhood, and Eli did not know. Sir/ma, whatever God has asked you to do and you keep disobeying, procrastinating, making excuses, rebelling, perverting his work or sinning against God, someone else is being raised who will obey God (1Sam.2.26). Judas was one of Jesus' 12 disciples but greed for money and ungodliness made him lose his ministry. This did not mess up God's plan for his church. Judas was replaced by Matthias (Acts.1.20-22). Notice that Matthias was with Jesus all the while Judas was with Jesus. Judas' replacement was being groomed all the while Judas was misbehaving. Let this wake you up today. If you keep disobeying God and living in sin, know this today, your replacement is nearby. Wake up!",
    ],
    meditationScripture: "Rom. 11:22",
    meditationText:
      "Notice how God is both kind and severe. He is severe to those who disobeyed, but kind to you as you continue to trust in his kindness. But if you stop trusting, you also will be cut off. (NLT)",
  },
  {
    date: "2026-07-15",
    title: "The Destroyer",
    scripture: "Mark 16:18",
    verseText: "They will be able to handle snakes with safety, and if they drink anything poisonous, it won't hurt them. They will be able to place their hands on the sick and heal them. (NLT)",
    discussion: [
      'When you hear the word; Destroyer! What comes to mind? Chaos, pandemonium, death and destruction. Right? For example, John 10:10 speaks of the thief coming to steal, kill and to destroy. Also, in Exodus, the death messenger moved through the entire land of Egypt, killing all the first born of humans and animals. This death messenger was called "The Destroyer" (Exod.12.23). When the Israelites murmured against God in the wilderness, venomous vipers crept out and killed many of them. These deadly snakes were referred to as "The Destroyer" (1Cor.10.10). So, we see that the destroyer represents one who attacks another by cancelling out his victim\'s existence or wellbeing. Therefore, to deliver us from being prey or victims of all that is evil, God gave us a superior life called Zoe. This is eternal life (1John 5:11), the life of God Himself; a oneness with the God-head (1Cor 6:17) and a partaker of His divine nature (2Peter 1:4). He delivered us out of the influence of the destroyer and transplanted us in the kingdom of the Lord Jesus (Col.1.13). One amazing thing about this Life itself is that it is also a destroyer of all that is evil. In other words, we not only were delivered from the reach of the destroyer (Satan, wicked spirits, sin, death, sicknesses etc), but we received the divine life that destroys sicknesses, death, and all the works of the devil. Hallelujah! When this life comes in contact with diseases for example, it destroys them and makes the person whole. How do we administer this life? By contact (Mark 16:18). Jesus instructs you to lay your hands on the sick in order to let Zoe make contact with the disease. The moment Zoe makes contact, it begins to destroy that disease and the person begins to recover. Oftentimes, nothing seems to be happening on the outside, but on the inside, the normal course of that infirmity has been hijacked, and a reversal begins. Recovery is imminent. Contact can also be made through your words. When you speak to the sick or oppressed, life flows and as it comes in contact with the infirmity, it destroys it and the person immediately begins to recover. Dear saint, you carry in you the demon destroying, sickness annihilating life of God. With this consciousness, go forth, releasing the life in you, destroying every infirmity that holds your loved ones bound. Something happens when you lay your hands. Keep laying those hands. Shalom Uvracha!',
    ],
    meditationScripture: "Mark 16:18",
    meditationText:
      "They will be able to handle snakes with safety, and if they drink anything poisonous, it won't hurt them. They will be able to place their hands on the sick and heal them. (NLT)",
  },
  {
    date: "2026-07-16",
    title: "The Silent Sin",
    scripture: "Prov. 23:20-21",
    verseText: "Do not join those who drink too much wine or gorge themselves on meat, for drunkards and gluttons become poor, and drowsiness clothes them in rags. (NIV)",
    discussion: [
      'When we hear the word "Sin", we often think of the obvious ones like fornication, adultery, stealing, lying and murder. Sometimes we need to remind ourselves of the subtle ones like malice, envy, hatred, and strife. Galatians chapter five lists all these as works of the flesh and clearly states that "...those who live like this will not inherit the kingdom of God." (Gal 5:21 NIV) Today we want to pay attention to the silent sin called gluttony. You hardly ever hear anyone talk about it as sin. With confidence, we call drunkenness sin. In our minds, we banish anyone drunk on alcohol to the flames of hell. We warn about the dangers of drinking alcohol, then on the other hand we praise someone who stuffs himself with food. Worse case, we recommend dieting for the person. Funny how we condemn everyone sitting in a beer parlor but celebrate those who eat more than they can in an all you can eat buffet. Do you not see that drunkenness and gluttony are twin sins? You can\'t vilify one and justify the other. The bible tells you to stay away from the sins of gluttony and drunkenness. You\'re neither to join those who get drunk nor those who eat too much. Prov.23.20-21; "Do not join those who drink too much wine or gorge themselves on meat, for drunkards and gluttons become poor, and drowsiness clothes them in rags." (NIV)',
      "The reason drunkenness and gluttony are both sins is because they are expressions of lack of self-control. Self-control is a fruit of the spirit, and the lack of it is a work of the flesh that produces many sins including drunkenness and gluttony. So, if you do not drink alcohol but you can't control your eating, you're still sinning and need to stop now. Gluttony isn't just a body damaging, health deteriorating habit like alcoholism, it's a sin that a believer must repent of. From now on, never lose yourself to any indulgence. Have self-control. Train yourself to refrain from anything that tries to get a hold of you and control you. One way to train yourself against gluttony and other selfish acts is by regular fasting, consistent praying, and meditating on God's word. If you would master the art of self-control in eating and drinking, it will soon trickle down to having self-control in sexual temptations, self-control in wrath, etc. The grace of God is at work in you and enables you walk in self-control. Shalom Uvracha!",
    ],
    meditationScripture: "Prov. 23:20-21",
    meditationText: "Do not join those who drink too much wine or gorge themselves on meat, for drunkards and gluttons become poor, and drowsiness clothes them in rags. (NIV)",
  },
  {
    date: "2026-07-17",
    title: "Beware of the Hijackers",
    scripture: "Jas. 1:5",
    verseText: "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
    discussion: [
      'What an inspiring scripture we have in James 1:5. When you ask, God will not grudgingly give you. He isn\'t into fault-finding. He will surely give you as you have asked. This reveals a prayer answering God. A God who is eager to grant your request for wisdom. Wisdom is at the bedrock of all our desires. For example, when you pray for money, what you\'re really asking for is the wisdom required to get the money needed. If you pray for a spouse, what you\'re really asking for is the wisdom you need to choose the right partner. So, James tells us that when we make such requests, God generously grants our requests. This is very good news, don\'t you think? Skip to verse seven and the story seems to change. Jas.1:7; "For let not that man think that he shall receive any thing of the Lord." Wait a minute. I thought he just said God gives liberally to all who ask him. How come he now says a certain man asking will not receive anything from God. What changed between verse five and verse seven? A hijacker clause was introduced. Surely, God will generously grant your request for wisdom, but your receiving will be greatly hindered if you are double minded. Jas.1.6; "But let him ask in faith, nothing wavering. For he that wavereth is like a wave of the sea driven with the wind and tossed."',
      'The criteria for your asking and receiving is to ask in faith. If you waver in your heart; doubting God\'s ability and willingness to grant your request, you have become double minded and your doublemindedness has hijacked the receiving process. Jas.1.8; "A double minded man is unstable in all his ways." Faith is singlemindedness; and singlemindedness is stability; and stability is required for answers to be received in prayer. Doublemindedness is usually revealed in our utterances and conversations after we have prayed. You can\'t pray for healing, then talk like God has not answered your prayer, and then you expect to miraculously be healed. If you have prayed, believe that God has answered you. How do you know He answered you? Because His word says He will. Then doubt-proof your heart so that your receiving doesn\'t get hijacked. Do this by constantly meditating on God\'s word concerning the request you have made. Where the heart that doubts gets nothing, the heart of faith gets a miracle. I celebrate your miracle. Hallelujah!',
    ],
    meditationScripture: "Mark 11:23-24",
    meditationText:
      "For verily I say unto you, That whosoever shall say unto this mountain, Be thou removed, and be thou cast into the sea; and shall not doubt in his heart, but shall believe that those things which he saith shall come to pass; he shall have whatsoever he saith. Therefore, I say unto you, What things soever ye desire, when ye pray, believe that ye receive them, and ye shall have them.",
  },
  {
    date: "2026-07-18",
    title: "Get into the New",
    scripture: "Lev. 26:10",
    verseText: "You shall eat the old harvest, and clear out the old because of the new. (NKJV)",
    discussion: [
      'Many times, in life, you will have to get rid of the old in order to embrace the new. Sometimes, it\'s not because the old has become bad or unprofitable, but because that\'s the only way for the new to come in. That\'s what our opening verse says. Lev.26.10; "You shall eat the old harvest, and clear out the old because of the new." (NKJV) While you\'re eating the old, the new will be beckoning to be let in, therefore the old will have to go to make space for the new. This is a parable of some sort. In Paul\'s day, he said something in this respect. Phil 3:13; "Brethren, I do not count myself to have apprehended; but one thing I do, forgetting those things which are behind and reaching forward to those things which are ahead." As Saul, he had so much going for him; a pharisee, a zealous adherent to the laws, a self-righteous persecutor of the church, respected by the leaders of his day. But after an encounter with Jesus, he had to let go of all these in order to embrace God\'s best for him. As a believer, Paul pressed forward and continued to experience greater revelation of the purposes of God and the miraculous display of God\'s power in ever increasing measure. Sometimes, we hang on to the past so much that it corrupts the present and hinders the future. A job that was a miracle in the past can become a stumbling block in the present. You will have to grow in the wisdom required to discern when God has moved. When He moves, you move! If you remain where God used to be, you will miss what He is currently doing. For some reading this today, a particular job has become the hinderance to the new. A relationship you\'re in has become the old that has to go for the new to come but you\'re holding on to it with the expectation that it\'ll graduate into marriage. But if you\'re going to be honest with yourself, you\'ll agree that God has moved forward but you\'re stuck in the past. It\'s time to let go of the old in order for the new to come in. And you know what? You most times have to let go of the old first before the new can come. For everything you have ever achieved in life, there is more. Celebrate and give thanks for current victories, but remember there\'s more. In your heart, build an altar of memorial at the point of each victory. This serves as a point of perpetual thanksgiving and encouragement as you press on for more. God has more for you, never let the past (good or bad) stop you from reaching out for God\'s best for you. Shalom Uvracha!',
    ],
    meditationScripture: "Lev. 26:10",
    meditationText: "You shall eat the old harvest, and clear out the old because of the new. (NKJV)",
  },
  {
    date: "2026-07-19",
    title: "2 Kinds of Responses",
    scripture: "1 Sam. 10:26-27",
    verseText:
      "When Saul returned to his home at Gibeah, a band of men whose hearts God had touched became his constant companions. But there were some wicked men who complained, \"How can this man save us?\" And they despised him and refused to bring him gifts. But Saul ignored them. (NLT)",
    discussion: [
      'Samuel had just anointed Saul to be king of Israel. This was a breakthrough moment for Saul, his family, the tribe of Benjamin, and all Israel. Saul went out in search of his father\'s donkeys, but came back the anointed king of Israel. Something notable happened right after Samuel announced Saul as the new king of Israel; a group of men became his constant companions. These became his immediate servants and guards. The bible clearly states that God touched their hearts. It wasn\'t something they were forced or begged to do. I want you to know that for every assignment God anoints you to carry out, there are men whose hearts God has touched to follow you and work with you to accomplish all that God has sent you to do. These will not follow you by coercion but by conviction. If you try to force people to follow you, you will get an unwilling crowd on your side. They may be with you physically, but their hearts aren\'t with you. You need men whose hearts are with you, and only God can make this happen. This applies to church leaders, entrepreneurs and business managers as well. There are staff that will work with you with all their hearts, while others will be there in body but their hearts are far from you and your company. Trust God to send you employees whose hearts are with you. Notice something else; there was another group of people who were referred to as wicked men. They complained about Saul\'s ordination. They reproached him and despised him.',
      'They wouldn\'t submit to him because they thought he wasn\'t qualified to lead them. Maybe they had better education than Saul had. Or they had superior qualifications. You know how to deal with this group? IGNORE THEM. Saul went with those whose hearts God had touched to follow him, and he ignored those who despised him. Likewise, there are those who see no reason why you should be promoted above them. They despise you, scoff at you and resist you. Never let this group bother you. Don\'t lose sleep over their behaviour. When you try so hard to get the support of this group, you are at risk of compromising God\'s call upon your life. You may get distracted and derail from God\'s assignment or the responsibilities committed to you at your duty post. This eventually happened to king Saul. Beware of those whose response is to despise you because God chose you. Don\'t engage them...ignore them. Focus on the work ahead and allow those whose hearts God has touched to serve with you as God has led them. Shalom Uvracha!',
    ],
    meditationScripture: "Prov. 4:25",
    meditationText: "Look straight ahead, and fix your eyes on what lies before you. (NLT)",
  },
  {
    date: "2026-07-20",
    title: "Ticking Bomb",
    scripture: "Acts 17:21",
    verseText: "For all the Athenians and strangers which were there spent their time in nothing else, but either to tell, or to hear some new thing.",
    discussion: [
      'The bane of the current church in many parts of Africa is the rising trend in godless preaching having little or nothing to do with the focus of Christ and the early apostles. Sermons that promote greed and self-seeking. Yet, the multitudes rejoice over such rhetoric. This is a ticking bomb that\'s soon to detonate if not quickly defused. Take a look at the number of times the Apostle Paul warns Timothy about the distraction of unprofitable doctrines. 1Tim.1.3; "...that thou mightest charge some that they teach no other doctrine." Don\'t teach any other doctrine different from what Christ and His apostles taught. 1Tim.1.4; "Neither give heed to fables and endless genealogies, which minister questions, rather than godly edifying which is in faith." Don\'t pay attention to fables, myths and endless ramblings that create more questions than answers and have no power to edify anyone to godly living. 1Tim.1.5; Love is the sum total of the laws, prophets, gospels, history books, the epistles and the apocalyptic books. The love of God revealed in Christ and the love of God lived out through His saints by the Holy Ghost. Whatever message you hear that does not propel you into a greater love walk, isn\'t the message of the kingdom of God. 1Tim.1.6; Some have turned away from love and have embraced vain janglings. In search of deep mysteries, they have become bereft of love for the saints. Like a sheep to the slaughter, they\'re slowly isolated from the flock of God in order to be destroyed by the devil. Beware! 1Tim.1.7; "Desiring to be teachers of the law; understanding neither what they say, nor whereof they affirm." They desire to be teachers, yet they do not understand what they teach. They\'re confused because they have mixed the bible with science, psychology, astrology, and other material laden with spiritually unprofitable information. A child of God must stay focused on growing in the knowledge of God in Christ Jesus. To stay focused, you must stay away from such distracting doctrines. 1Tim.4.7; "But refuse and avoid irreverent legends (profane and impure and godless fictions, mere grandmothers\' tales) and silly myths, and express your disapproval of them. Train yourself toward godliness (piety), [keeping yourself spiritually fit]." (AMP) Also, in Titus.3.9; "Do not get involved in foolish discussions about spiritual pedigrees...These kinds of things are useless and a waste of time." If we would adhere to these instructions, we would be safe and do well in the kingdom. Why ignore these clear warnings and go in search of forbidden knowledge that\'ll do you harm? Stay on course and grow in Him. Shalom Uvracha!',
    ],
    confession: "I stay focused on God's word. I refuse to give attention to distracting and destructive doctrines of men.",
  },
  {
    date: "2026-07-21",
    title: "By Many or by Few",
    scripture: "1 Sam. 14:6",
    verseText:
      "And Jonathan said to the young man that bare his armour, Come, and let us go over unto the garrison of these uncircumcised: it may be that the LORD will work for us: for there is no restraint to the LORD to save by many or by few.",
    discussion: [
      "Meditate on this today. Sometimes, we restrain ourselves from making the move we ought to make because we underestimate the power of God available to us. God's power is so powerfully demonstrated in raising Jesus from the dead: Eph.1.19-21; \"And what is the exceeding greatness of his power to us-ward who believe, according to the working of his mighty power, Which he wrought in Christ, when he raised him from the dead, and set him at his own right hand in the heavenly places, Far above all principality, and power, and might, and dominion, and every name that is named, not only in this world, but also in that which is to come.\" On account of this great demonstration of the divine power we are assured that nothing good is withheld from us: Read Rom.8.32. In our opening text, Jonathan and his assistant were faced with a garrison of the Philistines. It was impossible for only 2 men to take on a garrison. What outright audacity of faith! The secret of their faith is revealed in Jonathan's utterance; 1Sam.14:6; \"...for there is no restraint to the LORD to save by many or by few.\" In other words, the number of soldiers in your army is no advantage nor disadvantage to God. True to Jonathan's faith, the Lord wreaked havoc in the camp of the Philistines using just 2 men. 1Sam.14.13-15; \"And Jonathan climbed up upon his hands and upon his feet, and his armourbearer after him: and they fell before Jonathan; and his armourbearer slew after him. And that first slaughter, which Jonathan and his armourbearer made, was about twenty men, within as it were an half acre of land, which a yoke of oxen might Plow. And there was trembling in the host, in the field, and among all the people: the garrison, and the spoilers, they also trembled, and the earth quaked: so, it was a very great trembling.\"",
      "What a mighty result, just because 2 men chose to act by faith in God even against all odds! Beloved, whatever you consider to be your advantage or disadvantage is inconsequential to God. He is God all by Himself and has the power to bring things to pass out of nothing. Your faith matters far more than any other thing around you. By faith in God, you can rewrite your experiences even if everyone around you thinks you're incapable of anything great. By faith in God, move forward today! Hallelujah!",
    ],
    meditationScripture: "Eph. 3:20",
    meditationText: "Now unto him that is able to do exceeding abundantly above all that we ask or think, according to the power that worketh in us,",
  },
  {
    date: "2026-07-22",
    title: "Greater Than the Greatest",
    scripture: "Matt. 11:11",
    verseText: "Verily I say unto you, Among them that are born of women there hath not risen a greater than John the Baptist: notwithstanding he that is least in the kingdom of heaven is greater than he.",
    discussion: [
      "If you were asked who was the greatest man who ever lived before Christ, you'd probably choose someone like Enoch who transitioned without seeing death, or Moses who divided the red sea, or Elijah who called down fire from heaven, or Elisha who wrought amazing miracles until even his dead bones raised a dead man back to life. Surely, these are the greatest men born of women. But this isn't God's estimation. God does not see as men see, neither does He choose as men choose. According to the divine order of things, of all men born of women, there is none greater than John the Baptist. Think about it for a second. A man who did no miracles, lived in the wilderness, was incarcerated and decapitated. What made John the greatest man ever? Consider what made him unique: he was the forerunner of the long-expected messiah. He baptized, announced and introduced the long-awaited Christ to the Jews. This position of the Lord's announcer made him greater than all other prophets of old who were the Lord's foretellers.",
      "Get this; greatness before God is only in relation to the Christ. Then in one sweeping move, Jesus reveals that the least in this new kingdom is greater than John (Matt 11:11). If John's unique position made him the greatest born of women, then it must be that those who belong to the kingdom of God differ from John in position. As the prophets of old were foretellers of the Christ, and John was the announcer of the Christ, we in the kingdom of God are the witnesses of Christ. An announcer is greater than a foreteller, and a witness is greater than them all (Acts.1.8). Thus, with respect to Christ, the foretellers spoke of Christ's coming; the announcer declared that Christ is here; and the witnesses now show forth the results of His finished work. They spoke of a kingdom to come, but we live in the kingdom they prophesied about. Hallelujah! If John was the greatest of all men born of women, we are greater than the greatest of all. Not by works, but by grace. We are those who have received the grace of our Lord Jesus and have been made sons of God by the indwelling spirit of God. Knowing this, we do not function like Elijah or Moses, nor do we function like Jeremiah or Isaiah. No! We function as Jesus functioned because as He is the son of God, so has He made us also sons of God. Hallelujah!",
    ],
    meditationScripture: "Heb. 2:11",
    meditationText: "For both he that sanctifieth and they who are sanctified are all of one: for which cause he is not ashamed to call them brethren,",
  },
  {
    date: "2026-07-23",
    title: "The Lord Is with You",
    scripture: "1 Sam. 18:14-15",
    verseText: "David continued to succeed in everything he did, for the LORD was with him. When Saul recognized this, he became even more afraid of them. (NLT)",
    discussion: [
      'When we read through the bible, we see a particular trademark of success on everyone who God\'s presence was with. From Abraham, Isaac and Jacob, to Joseph, Nehemiah, Daniel and Paul. All succeeded in their divine assignments because God was with them. These men worked hard and prayed hard but their success was attributed to the presence of God, or what Paul called the grace of God; 1Cor.15.10; "But by the grace of God I am what I am: and his grace which was bestowed upon me was not in vain; but I laboured more abundantly than they all: yet not I, but the grace of God which was with me." David was recruited into King Saul\'s work force and although King Saul saw him as an enemy and plotted to kill him, David succeeded in everything he did and this made his enemy even more afraid of him. There is a lesson here for our generation who have been taught to pay too much attention to their enemies. From the prayers we pray these days, it seems as though everyone in our family, offices, neighbourhood, and even church are our enemies. This is breeding a community of suspicious anti-brethren. Everyone suspecting everybody of planning to harm somebody. What kind of evil is this?',
      "There are two notable things that happen when God's presence is with you: (1) You will continue to succeed in everything you do. (2) Your enemies will recognize that God's presence is with you and will become more afraid of you.",
      "Hallelujah! Where is the place for fear and panic here? No place at all. A child of God is far superior to all enemies. Stop being afraid that they can hurt you, or stop you from succeeding. If they couldn't stop Joseph or Daniel, how can they stop you? Don't you see that the presence of God is even more with you than it was with Moses and all the patriarchs? No more fears! No more panicking! No more looking for prayers here and there! You're not one looking for deliverance; you are the delivered one (Col 1:13). You're not the one looking for God's presence, He dwells in you already (1John 4:4). You are not the one looking for victory; you're the one victorious already (2Corinth 2:14). You're not the one trying to conquer; you are more than a conqueror already (Rom 8:37). Instead of focusing on the enemies, do like these fathers of old; focus on God's presence. Be conscious of His presence everywhere you go and in everything you do. Have faith in His presence with you than in the enemies against you. Success is yours in Jesus name! Shalom Uvracha!",
    ],
    meditationScripture: "Rom. 8:37",
    meditationText: "Nay, in all these things we are more than conquerors through him that loved us.",
  },
  {
    date: "2026-07-24",
    title: "Sent by God",
    scripture: "Ps. 105:17-18",
    verseText: "He sent a man before them, even Joseph, who was sold for a servant: Whose feet they hurt with fetters: he was laid in iron.",
    discussion: [
      "If God tells you he is sending somebody to help you or to make a way for you, you'll automatically expect to see a person of great influence, wealth or power. But this isn't always so. Not understanding the ways of God has made many of God's children miss God's best for them. Many have chased away their divinely sent helper because he/she didn't look like a helper. You need to understand that the one sent by God to help you in 5 years' time may first need your help today. Never treat anyone badly. Be kind to everyone, including those who seem not to deserve it. God's helper to you will not always look the part. So, it was with Joseph. The bible says God sent Joseph to preserve Israel, Egypt and other nations. How did God send him? Ps.105.17-18; He was sold as a slave, chained like a common animal, and sent even to prison. Yet, all this time, he was the man sent by God to preserve the very people who disregarded him. Ps.105.19; Between the receiving of the prophecy and the fulfilment of the prophecy, the word of God tried Joseph. This means that he was going through the refinery of God's word in order to flush out every hinderance to God's will and prepare him to be a vessel suitable for God's use. The difference between raw material and finished product is process.",
      "The platform on which process creates God's will is time. The person you see as a non-entity today could become a big-entity tomorrow; the difference is process over time. The word of God builds people over time. For you who is sent to others but are getting discouraged right now because you don't seem to be making any progress; refuse to be discouraged. Remember Joseph's preparation. You're going through your preparation as well. The word of God is trying you and it isn't always convenient. But if you go through your process successfully, you'll be a vessel for fulfilling God's agenda on the earth. Finally, to you who is expecting help from God, remember that your helper from God may look like a useless slave like Joseph in prison. If you will be faithful in being kind to 'Joseph', one day Joseph will no longer be a slave but a King and he will deliver you and your land from famine. Selah!",
    ],
    meditationScripture: "Heb. 13:2",
    meditationText: "Be not forgetful to entertain strangers: for thereby some have entertained angels unawares.",
  },
  {
    date: "2026-07-25",
    title: "Praising God",
    scripture: "2 Chr. 20:22",
    verseText: "And when they began to sing and to praise, the LORD set ambushments against the children of Ammon, Moab, and mount Seir, which were come against Judah; and they were smitten.",
    discussion: [
      'Think about these honest but grossly unfounded statements by some of our beloved brethren; \'the only thing God eats is praise, so give God His food\'...\'praise moves the hand of God\'...\'when praises go up, blessings come down\', etc. I\'m not even going to spend time scripturally demolishing these statements. Let\'s just focus on what the bible teaches. Firstly, when we praise God, we\'re calling to mind His wondrous works and telling forth His glorious deeds. Ps.107.8; "Oh that men would praise the LORD for his goodness, and for his wonderful works to the children of men!" What are some of His wonderful works to men? Ps.107.9; "For he satisfieth the longing soul, and filleth the hungry soul with goodness." Also Ps.107.16; "For he hath broken the gates of brass, and cut the bars of iron in sunder." These and more He has done, so the bible admonishes us to; Ps.107.22; "...sacrifice the sacrifices of thanksgiving, and declare his works with rejoicing." And so, this is what king Jehoshaphat did when he was faced with the brutal armies of three deadly nations; Ammon, Moab and Mount Seir. He put singers ahead of the troop, and as they sang praises to God, the Lord supernaturally defeated the enemy nations (2Chr.20.22). Hallelujah! Reading the entire story, you\'ll discover that it wasn\'t praise that brought about the victory; it was faith in God.',
      'The prophetic word had come forth. 2Chr.20.14-17; "Then upon Jahaziel...came the Spirit of the LORD...And he said...Thus saith the LORD unto you, Be not afraid nor dismayed by reason of this great multitude; for the battle is not yours, but God\'s...Ye shall not need to fight in this battle: set yourselves, stand ye still, and see the salvation of the LORD with you, O Judah and Jerusalem: fear not, nor be dismayed; tomorrow go out against them: for the LORD will be with you." The command wasn\'t to praise God, but that they will not need to fight in this war. Thus, Jehoshaphat acted in faith. Faith in God\'s word. He praised God because he believed God\'s word. Praising God isn\'t a way to bribe God to do something for you. Praising Him is because you believe His word and His ability to bring it to pass. When you praise God, your mind switches from focusing on the problem to focusing on God\'s infinite ability. Don\'t worry anymore, praise God today! Shalom!',
    ],
    action: "Think about what God has said to you concerning that matter. Sing praises to Him today for His mighty works. Expect great miracles!",
  },
  {
    date: "2026-07-26",
    title: "For the Sake of God's Will",
    scripture: "1 Sam. 23:17",
    verseText: "And he said unto him, Fear not: for the hand of Saul my father shall not find thee; and thou shalt be king over Israel, and I shall be next unto thee; and that also Saul my father knoweth.",
    discussion: [
      "Jonathan was King Saul's son and natural heir to the throne of Israel, but David was the anointed next-in-line King of Israel. So, there was the natural order of things, and then there was the divine order. Jonathan knew he was next in line to be king, but he also knew that David had been chosen and anointed by God to be king. Jonathan had to make a choice between his personal ambitions and the will of God. Listen, for the sake of God's will, you may sometimes have to lay aside your personal ambitions. King Saul couldn't lay aside his personal ambitions for God's will. He plotted and devised strategies to kill David. He also resented Jonathan for submitting to God's will for David to be King. Read what Saul says to Jonathan; 1Sam.20.31; \"For as long as the son of Jesse liveth upon the ground, thou shalt not be established, nor thy kingdom. Wherefore now send and fetch him unto me, for he shall surely die.\" This describes the two kinds of men we have on earth; the Saul kind, and the Jonathan kind. If you find yourself desperately pursuing personal ambitions, career, money, promotion, properties etc against what you know to be God's will, then know that you are a Saul kind of person.",
      'Such people don\'t even mind harming other people as long as it helps them preserve their selfish desires. Just as Saul missed out on God\'s plan and lost everything, likewise, anyone who pursues personal desires against the will of God will miss out on God\'s plan and will be at risk of losing all at the end; Mark.8.36; "For what shall it profit a man, if he shall gain the whole world, and lose his own soul?" On the other hand, Jonathan was a foreshadow of the coming Christ who in the garden of Gethsemane chose the will of God above His own personal desire; Luke.22.42; "Saying, Father, if thou be willing, remove this cup from me: nevertheless, not my will, but thine, be done." Jesus chose to do the Father\'s will and this resulted in the establishing of the kingdom of God in the earth. God\'s will and plan is always greater and better than our highest ambitions. We lose out when we are self-centred and gain all when we\'re God-centred. In everything you do today and forever, always choose to do God\'s will. Shalom Uvracha!',
      "For today's meditation, read John 5:30 (AMP).",
    ],
  },
  {
    date: "2026-07-27",
    title: "The Instructions Haven't Changed",
    scripture: "Matt. 6:5",
    verseText: "And when thou prayest, thou shalt not be as the hypocrites are: for they love to pray standing in the synagogues and in the corners of the streets, that they may be seen of men. Verily I say unto you, They have their reward.",
    discussion: [
      'These days we act as if the instructions Jesus gave about prayers have suddenly become obsolete. Listen to Jesus on prayer; Matt.6.5-9; "And when you come before God, don\'t turn that into a theatrical production either. All these people making a regular show out of their prayers, hoping for stardom! Do you think God sits in a box seat? Here\'s what I want you to do: Find a quiet, secluded place so you won\'t be tempted to role-play before God. Just be there as simply and honestly as you can manage. The focus will shift from you to God, and you will begin to sense his grace. The world is full of so-called prayer warriors who are prayer-ignorant. They\'re full of formulas and programs and advice, peddling techniques for getting what you want from God. Don\'t fall for that nonsense. This is your Father you are dealing with, and he knows better than you what you need. With a God like this loving you, you can pray very simply. Like this: Our Father in heaven, Reveal who you are." (MSG)',
      "Take note of these phrases; 'theatrical production', 'regular show', 'hoping for stardom', 'tempted to roleplay'. When it comes to prayer, these are all self-centred phrases indicating a desire for self-glory and self-praise. This has become very popular in our day. Too many people peddling techniques and formulae for getting what you want from God. Jesus teaches us to pray in a way that takes away public accolades and redirects our focus to God. Prayer that keeps the focus on you and how men will admire you, misses the whole reason for prayer which is to have communication with your heavenly Father. Some get carried away trying to imitate someone else's prayer gestures. As much as we learn from each other, we must remember prayer isn't imitation but communication. Don't fall for the temptation to put up a prayer show. It's not necessary to take pictures of yourself when praying so you can post it on social media. Instead of spending your energy trying to publicize your praying, rather, spend the time and energy in the real prayer. There is a place for advertising to invite brethren to join you in a prayer meeting, but there is also that wrong place where you're acting like those pharisees in Jesus' day; seeking the admiration of men. Take heed! Judge your motive. The wrong motive could make you lose your rewards. Shalom Uvracha!",
    ],
    meditationScripture: "Matt. 6:5",
    meditationText:
      "And when thou prayest, thou shalt not be as the hypocrites are: for they love to pray standing in the synagogues and in the corners of the streets, that they may be seen of men. Verily I say unto you, They have their reward.",
  },
  {
    date: "2026-07-28",
    title: "Don't Submit to What You've Already Defeated",
    scripture: "1 Sam. 28:6",
    verseText: "Saul prayed to GOD, but GOD didn't answer--neither by dream nor by sign nor by prophet. (MSG)",
    discussion: [
      'Son of God, be strong in the lord and in the power of His might! (Eph 6:10). Never let your guard down, the devil is always seeking opportunity to devour you (1Peter 5:8). You have walked with God for some time and by His grace have overcome some old habits. You have defeated certain things that used to hold you bound. You have broken free and begun to enjoy the sweet life of victory. This is great! This was King Saul\'s story. He drove out all the witches and mediums in Israel. He killed some of them, completely ridding the land of all witches and mediums. 1Sam.28.3; "...And Saul had put away those that had familiar spirits, and the wizards, out of the land." Israel had been polluted by this evil, but Saul cleansed the land so that everyone could worship only the Lord God.',
      "Overtime, Saul began to allow envy and anger to fester in his heart against David. Before long, this degenerated into depression and murderous intent. Then the Philistines came to battle against Israel and king Saul prayed to God for direction, but his heart had become too polluted to hear God. Instead of repenting and waiting patiently in the presence of God to seek God's mind, he immediately sought an alternative to the voice of God. He went to seek for the very witches/mediums he had driven out of Israel (1Sam.28.5-7). He went back to seek help from what he had driven out of his life. Sin does that. Sin gradually erodes your ability to truly repent and wait patiently on God. Dear brother/sister, don't submit to what you have already defeated! Don't succumb to the pressures of sin and evil. Don't go back to the pit you have come out from. Don't seek out witch doctors for help. Don't patronize people with familiar spirits pretending to be ministers of God. These things weaken your spirit and make you increasingly susceptible to more wicked spirits. Don't return to Egypt.",
      "If you do, it'll be worse this time than it previously was. You are more than a conqueror in Christ Jesus (Rom 8:37). Wait on God. Wait for Him. There is neither shame nor defeat to them who wait on Him. Shalom Uvracha!",
    ],
    meditationScripture: "Prov. 26:11",
    meditationText: "As a dog returneth to his vomit, so a fool returneth to his folly.",
  },
  {
    date: "2026-07-29",
    title: "Tell It Not in Gath",
    scripture: "2 Sam. 1:20",
    verseText: "Tell it not in Gath, publish it not in the streets of Askelon; lest the daughters of the Philistines rejoice, lest the daughters of the uncircumcised triumph.",
    discussion: [
      'David exemplified a true believer\'s character in more ways than one. Especially in the way he often handled conflict with king Saul. King Saul was anointed to be king, and even though he had become divinely rejected, David still honoured him as the anointed of God. Just because an anointed minister of God has derailed and become rebellious doesn\'t give you the right to dishonour him/her. This is what David\'s life teaches us. We urgently need this lesson in our day and time where we are ever so eager to crucify our fallen brethren and publicly condemn our ailing anointed. David had opportunity to take vengeance on King Saul but he turned each opportunity down. Eventually, King Saul and his son Jonathan were killed in battle and here was David\'s response at the receiving of the news; 2Sam 1.20; "Tell it not in Gath, publish it not in the streets of Askelon; lest the daughters of the Philistines rejoice, lest the daughters of the uncircumcised triumph." In other words, David was saying; don\'t speak publicly about Saul\'s demise; don\'t post it on social media; don\'t broadcast it on your status; don\'t discuss it on public platforms. Aren\'t these the very things we find ourselves doing these days? Why shouldn\'t we announce the fall of our brethren in public spaces? David says; "...lest the daughters of the Philistines rejoice, lest the daughters of the uncircumcised triumph." See that? He feared that the daughters of the Philistines will have occasion to mock God\'s people.',
      'When we wash our dirty linen in public, we give occasion for the unbelievers to mock us. Our public fights make it difficult for the unsaved to see the need for salvation in Christ Jesus alone. When they see us crucify our wounded soldiers, they doubt the efficacy of our gospel. We must never let our petty differences and selfish squabbles cause men to find it difficult to receive the gospel. In our natural families, there goes the saying; \'what happens in the family, stays in the family\'. If the privacy of our physical families matters so much to us, why then will personal matters of our spiritual family matter less? As imperfect as our physical family members are, we never put up their failures for the general public to discuss, how much more our spiritual families. There are ways to settle matters in our kingdom family. Jesus tells us; Matt.18.14-16; "If a fellow believer hurts you, go and tell him--work it out between the two of you. If he listens, you\'ve made a friend. If he won\'t listen, take one or two others along so that the presence of witnesses will keep things honest, and try again. If he still won\'t listen, tell the church. If he won\'t listen to the church, you\'ll have to start over from scratch, confront him with the need for repentance, and offer again God\'s forgiving love." (MSG) Read again and observe how kingdom hurts are handled in-house and in love. Never to destroy but to restore! Never to tear down but to build up! Never to mock but to love! Let this guide your steps onwards. Shalom Uvracha!',
    ],
  },
  {
    date: "2026-07-30",
    title: "The Terror of the Lord",
    scripture: "2 Cor. 5:10-11",
    verseText: "Knowing therefore the terror of the Lord, we persuade men; but we are made manifest unto God; and I trust also are made manifest in your consciences.",
    discussion: [
      "We preach the gospel and persuade all men to live righteously and carry-on good works in the kingdom of God. You hardly can turn any direction online or physically without encountering the preaching of the kingdom of God in one way or another. In many places, churches are within a walking distance, while in other places where there aren't churches, everyone can connect to a church through their electronic devices. The gospel is spreading through every godly ministry and the kingdom of God is swallowing up the whole earth. Hallelujah! Yes, I know there are fake churches and false preachers, but they are only proof of the true ones, for there cannot be fake without original. The truth will outlive the lie; the false will expire while the truth endures forever.",
      'The reason we keep preaching all over the earth and keep earnestly persuading men in every place is because we know the terror of the Lord. The terror of the Lord is not wrath, brimstone and repugnant sulphur as many have thought. The terror of the Lord is not the tortures of violent flames as many presume. Death, hell and the lake of fire are real but aren\'t the terror of the Lord but are the judgment of the wicked. The scriptures reveal to us what the terror of the Lord is; 2Cor.5.10-11; "For we must all appear before the judgment seat of Christ; that every one may receive the things done in his body, according to that he hath done, whether it be good or bad. Knowing therefore the terror of the Lord, we persuade men..." So, what is the terror of the Lord? It is the judgment seat of Christ where everyone will be rewarded for what he or she did while in their body. Thus, the terror of the Lord is His reward system. This is one area we have greatly undermined in our day. We talk much about heaven and hell, so everyone just wants to escape hell and make heaven, and all it takes to do that is to believe in your heart that Jesus is the Son of God who rose from the dead. We often fail to realize that the reason we\'re still left on earth to carry out the works of the kingdom isn\'t for the purpose of making heaven, but for the purpose of getting rewards. It\'s called the terror of the Lord because it is righteous and cannot be influenced by your emotions or weeping. These are eternal rewards we will receive in our new bodies. These are not gifts but rewards, therefore what you do now will determine the rewards you will receive at the resurrection of the just. If you understand this, you will never need anyone to encourage you to serve God today. Be devoted to your local assembly; preach the gospel in your environment; heal the sick, cast out devils, help the poor, support the planting of churches, strengthen the weak, etc. You will receive eternal rewards for these things. There will be no mix ups or oversights, you will be rewarded for what you did, so get busy and quit giving excuses. Eternal rewards are at stake. Shalom Uvracha!',
    ],
  },
  {
    date: "2026-07-31",
    title: "Purifier",
    scripture: "Prov. 17:3",
    verseText: "The fining pot is for silver, and the furnace for gold: but the LORD trieth the hearts.",
    discussion: [
      'Raw gold has to be smelted in the furnace to make it pure and suitable for honourable use. It gets better by purification and it gets purer by fire. Raw silver endures extreme temperatures in a crucible in order for it to become usable by the end users and highly profitable to the sellers. Silver gets better when it\'s purer, and it gets purer by fire. The bible is saying to us that we are as gold and as silver; we become better when we\'re purer, and we get purer by fire. So, Gold is refined by the refiner\'s furnace; silver is refined by the refiner\'s furnace; and we are refined when God tries our hearts. How does God try our hearts? Heb.4.12; "For the word of God is quick, and powerful, and sharper than any two-edged sword, piercing even to the dividing asunder of soul and spirit, and of the joints and marrow, and is a discerner of the thoughts and intents of the heart." The word of God. How does God try our hearts? Jas.1.2-3; "My brethren, count it all joy when ye fall into divers temptations; Knowing this, that the trying of your faith worketh patience." Read 1Pet.1.7; "That the trial of your faith, being much more precious than of gold that perisheth, though it be tried with fire, might be found unto praise and honour and glory at the appearing of Jesus Christ:"',
      'So, we see that the refining pot for a child of God is (1) The word of God (2) Trials. Thus, we get better when we get purer; we get purer when we give ourselves to the hearing of God\'s word and when we go through trials. The one who hardly listens to the word of God will remain largely impure in conduct. A little trial will expose such a person\'s carnality. The purer we are, the more fit we become for the master\'s use; 2Tim.2.19-21; "...And, Let everyone that nameth the name of Christ depart from iniquity. But in a great house there are not only vessels of gold and of silver, but also of wood and of earth; and some to honour, and some to dishonour. If a man therefore purge himself from these, he shall be a vessel unto honour, sanctified, and meet for the master\'s use, and prepared unto every good work." Child of God, purge yourself from all impurity by surrendering yourself to the teaching of God\'s word and rejoice when you go through trials of your faith. God is always willing and ready to use you, therefore make yourself usable. Shalom Uvracha!',
    ],
    meditationScripture: "2 Tim. 2:21",
    meditationText: "If you keep yourself pure, you will be a utensil God can use for his purpose. Your life will be clean, and you will be ready for the Master to use you for every good work. (NLT)",
  },
];
